# Generated by Django 2.2 on 2019-04-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_tbl_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_text',
        ),
    ]
