# Generated by Django 2.2 on 2019-04-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_tbl_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_text',
        ),
    ]
