# Generated by Django 2.2 on 2019-04-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_delete_tbl_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputtxt', models.CharField(max_length=10000000000000)),
                ('outputtxt', models.CharField(max_length=10000000000000)),
                ('audio', models.FileField(blank=True, null=True, upload_to='media', verbose_name='file')),
            ],
        ),
    ]
