# Generated by Django 2.2 on 2019-04-12 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_tbl_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_text',
        ),
    ]
