# Generated by Django 2.2 on 2019-04-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_delete_tbl_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputtype', models.CharField(max_length=50)),
                ('inputtxt', models.CharField(max_length=10000000000000)),
                ('outputtxt', models.CharField(max_length=10000000000000)),
                ('audio', models.FileField(blank=True, null=True, upload_to='', verbose_name='file')),
            ],
        ),
    ]
