# Generated by Django 2.2 on 2019-04-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_tbl_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_contact',
        ),
        migrations.DeleteModel(
            name='tbl_log',
        ),
        migrations.DeleteModel(
            name='tbl_reg',
        ),
        migrations.DeleteModel(
            name='tbl_text',
        ),
    ]
