# Generated by Django 2.2 on 2019-04-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0012_auto_20190424_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=1000)),
                ('message', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('usertype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('approve', models.CharField(max_length=50)),
                ('usertype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputtype', models.CharField(max_length=50)),
                ('inputtxt', models.CharField(max_length=10000000000000)),
                ('outputtxt', models.CharField(max_length=10000000000000)),
                ('audio', models.FileField(blank=True, null=True, upload_to='', verbose_name='file')),
            ],
        ),
    ]
